language: perl

sudo: false

perl:
    - "5.26"
    
addons:
    apt:
        packages:
            - gzip

install:
    - "export PATH=$PWD/bin:$PATH"

script:
    - "skrofula --version"
    - "skrofula --help"
    - "cd perl5/Biotool && for M in *.pm ; do perl $M ; done"
